# Generated by Django 4.2.8 on 2024-02-28 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employe', '0002_employee'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Tirle of the vacancy')),
                ('salary_from', models.PositiveIntegerField(verbose_name='Salary starts from (USD)')),
                ('salary_to', models.PositiveBigIntegerField(verbose_name='Salary ends in(USD)')),
                ('description', models.TextField(verbose_name='description of the vacancy')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='vacancy pub')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employer.employer', verbose_name='Company')),
                ('required_skills', models.ManyToManyField(to='employe.employeskill', verbose_name='Required_skills')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
            },
        ),
    ]
