# Generated by Django 4.2.8 on 2024-02-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'EmployeSkill',
                'verbose_name_plural': 'EmployeSkills',
            },
        ),
    ]
